{% set name = "ldas-tools-ldasgen" %}
{% set version = "2.7.0" %}
{% set sha256 = "00e09df1e56b7168e81f36a55ceb127a7706bede52eafa8409f9c2c697067e2e" %}

{% set ldas_tools_al_version = "2.6.3" %}
{% set ldas_tools_cmake_version = "1.0.8" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-ldasgen", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - flex
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - openssl
    - zlib
  run:
    - ldas-tools-al >={{ ldas_tools_al_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - test -f ${PREFIX}/lib/libldasgen${SHLIB_EXT}  # [unix]
    - pkg-config --print-errors --modversion ldastools-ldasgen  # [unix]

about:
  home: "https://wiki.ligo.org/Computing/LDASTools"
  dev_url: "https://git.ligo.org/ldastools/LDAS_Tools"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "Filters library used by ldas-tools"
  description: |
    This provides the runtime libraries for the filters library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
