{% set name = "ldas-tools-ldasgen" %}
{% set version = "2.7.2" %}
{% set sha256 = "68fbd227b45468aa6ea4a1519b42e13cdf55eed2567b5a2f6fbe7fdc908d748e" %}

{% set ldas_tools_al_version = "2.6.6" %}
{% set ldas_tools_cmake_version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-ldasgen", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
  run:
    - ldas-tools-al >={{ ldas_tools_al_version }}

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/lib/libldasgen${SHLIB_EXT}  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} ldastools-ldasgen

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Filters library used by ldas-tools
  description: |
    This provides the runtime libraries for the filters library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
