{% set name = "ldas-tools-ldasgen" %}
{% set version = "2.7.3" %}

{% set ldas_tools_al_version = "2.6.7" %}
{% set ldas_tools_cmake_version = "1.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: af3b90cdcf647f7091dadcd247185637791c00939174c1c7836ca3700387e7aa

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-ldasgen", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
  run:
    - ldas-tools-al >={{ ldas_tools_al_version }}

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/lib/libldasgen${SHLIB_EXT}  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} ldastools-ldasgen

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Filters library used by ldas-tools
  description: |
    This provides the runtime libraries for the filters library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
