travis:
  secure:
    BINSTAR_TOKEN: e2AOmJCOaB8hk7pqB89ZRkly5TKuI8riLAV+vIJ5cVJgTN2Pf1FjmBmk+PGJ/mw2cxZwszS91fW159oTdTmi4eSWwsVGS2D14c/+kGQObxv6OyN/iUYNg0f6zgmL2Mhrk349ymnJmv1eimPQJQcN+bfvMrzjrt4KQhWdR3LYBFw2cjuR0dtlkqG/wlG5Mgoc4fZEON0SgU3Mo1Xtiw11VjFkqlBFZBh8azr22/8ghfDzHIBSetDwf6UH1FtSU2WjXNhzgZ9EAtatr7O4iGAoiQYNGs2z+svMQLzES+ksRFaDF5B7yn4OFbZXRKRvlW9zGCdkFtWcs9TWIFWkWMYmPntJdBQ0xTMkQQ5EvEf+cshqvNBB8DER0kkTWTVfrZSLcZQ4S9+5ARL5WSBTxK3KCO7cHqDQsYOMQXDYAe5w5GkMqSqy0XFAcuOZ6X2k2K5ApdvmmhWmSqL7zAPg7gaT7hTrzTTl1XnQGBk1mQ6HA2d/QxTA4pYYqi3zDCc8/RwcN/ImUujZeFXZRF38qtelnkAhUPXfs+IkkuJszV5FyQeqzNOfgRnRkm8+rQ82J8Ql2p0zJDoWSVcLO8vpmZKP87cAOsx2ro4MfYeTGeZa8syqqcSnJ8PjF5G1RATSc2erPQGrgBfodNpfsKH8uHMjBr3yCcQKm+xIU+JbLo3f1rA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
