travis:
  secure:
    BINSTAR_TOKEN: TnIWvRn0S1oYo3HNJ3c6mcbpnymyF2rj5hyzIOjuEBdDhJiiJu4b1mr+E/o2aDOlxcblEMOhIl6CBGZhHMErGvJr2XB9d5In5PSXq8YnbqC8UHFDsPQvO6mD/lN2HF1bCV9L4SuAebkB9JKHi2Sk7eT+5fMATN7U7UuiCN5/a1i76fRLZ35RFFb4WJffFccsnMlq8PwuRI8GaYohtYrzh8Z1jJJz5UzJneyS+98Uvolg350AzyhW7+yrwxszNjVPrOnrfbCDSztnYdZMXqHCyaxjPYXMLhlcbhttlO1pW3iTfPrqLcT+X05REZqm2xKU9HAmYyPjTNnY8btB1PBLu4qTW8koQTj8yWOyRv4eEsweE1su5lANrRTl2do8m0fh//Wjs8UluzH7vhnbfa+rHyLmu4mB0FGNgqYEWgxwB7wm0toCWpLHeMz8zVDAXzaSIMEY7q6KsCkk2Apa24zLv3gmPrPx0r7BwNW+432ivLkC7gXot47QldoDxIpaN83DXHi09ZPneLDQflB4UL1uwSlMDy47QbJWs1o498Qrw/0+g1Xz+Xq2FpzRDqLMfTkh0+XvdDkIa/3lI7wcvNClP175jqNuwDpeBGQAp9C/wnrKQ0TV3qB35jVYF4dC/95aIpkTobW0slrtM1PfN+5qSwkrTZkTgFjWbB1W10RvT5I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
