travis:
  secure:
    BINSTAR_TOKEN: odTN8tP+ajd7UwicanzaeC2/zOCQ2vhZKx3UuHVjmODUUm9rm/xKQ3okFy+PrCPrxmw/joArkoUo/RQyC1ix1fhIc1ZAYpo4T+0oznPmER4+XWn7rqF2GkbGlK/dlsAZ1MtffUMmx2fDJ/9e0CDRkOgWKEipGvUuRsq7ROaxtBODHFnU0hnlPxLkqbX8O0CxEBrm+TiqZNF1eB3+CAyC7M/iyCUtx5Fn2cGFoIDFpKp3A6TIblMO1sSNfAgF4puVId8DYLey5aSZdgUylNu9jVq69bzbvYHi8pch6Y1UWne0EM2nySvfTOG0AqXJsRU0FBTFRMpUVMetRoOQXVQ7BIEmunZH9PSmhBiBmeNn/TLeS4kKpE+Dd1e0ptppD/4CYi95lwn8Q4Y2f6vNatv0Ka/5WfpTXTutj0YR/2+tEC9Og9oyhu87d9+zeSr5N+Oy6bRcnGqmnnEqINGKx/ZkqHfhzIV0sRXYOQMsXzWPv2Vl/a7sFJnzK5DnId14pa2uvQg0rYF0pDQ2tcQkhUJAf/coWBFf7qEoABQYltyz5ut4koxySImSXQdgRiZBaInmXRqBOcSmSCMcK0BwSLKZtTD71CQpDYDjJPu+rgb5J6iT1ZGmvaLfIcPojPVklmR3YoqLvuTY+RdNcHydN5BwR4vivlkzP25LgEPQOKLpebE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
